project:
  type: website
  output-dir: docs

website:
  title: "Jade O'Brien"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: cv.qmd
        text: CV

format:
  html:
    theme: pulse
    css: styles.css
    toc: false
    width: 1700
    page-layout: full

editor: source

