---
title: "Projects"
fontsize: 1.39em  
include-in-header:
  text: |
    <link rel="shortcut icon" href="trans_icon.png" />
    <link rel="icon" type="image/x-icon" href="docu_favi.jpg">

---

<div>
(2025\) Li I., <b> O'Brien J. </b>, Pan D., Bao L., Vasquez C., McPhilips E. "Validation of Oceanographic Data Products and Investigation of Ocean Acidification and Its Biological Impacts"

(2024\) <b> O’Brien J. </b>, Iyer A., Tran D., Kennedy A. <a href="ISI-BUDS_Project_Report_Draft.pdf"> “Mental Health Outcomes of Internally Displaced Sexual Minority Men in Ukraine” </a>

(2024\) <a href="breast-detection.html">"Breast Mass Biopsy Classification"</a>

(2024\) "Vocal Deepfake Detection". <a href="https://www.soundethics.org/">Sound Ethics</a>

## Presentations

Li I., <b> O'Brien J. </b>, Pan D., Bao L., Vasquez C., McPhilips E. (2025, June). <a href="CalCOFI poster.png">"Validation of Oceanographic Data Products and Investigation of Ocean Acidification and Its Biological Impacts"</a>. UCSB Data Science Capstone Poster Session.

<b> O’Brien J. </b>, Iyer A., Tran D., Kennedy A. (2024, August). “Mental Health Outcomes of Internally Displaced Sexual Minority Men in Ukraine”. ISI-BUDS Closing Symposium.

<b> O’Brien J. </b>, Iyer A., Tran D., Kennedy A. (2024, November). “Mental Health Outcomes of Internally Displaced Sexual Minority Men in Ukraine”. eUSR Video Presentations.

</div>

